/* tslint:disable */
/* eslint-disable */
/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { IngestionBatchRequest } from '../models';
// @ts-ignore
import { IngestionEvent } from '../models';
// @ts-ignore
import { IngestionResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * IngestionApi - axios parameter creator
 * @export
 */
export const IngestionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Batched ingestion for Langfuse Tracing
         * @param {IngestionBatchRequest} ingestionBatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batch: async (ingestionBatchRequest: IngestionBatchRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ingestionBatchRequest' is not null or undefined
            assertParamExists('batch', 'ingestionBatchRequest', ingestionBatchRequest)
            const localVarPath = `/api/public/ingestion`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: ingestionBatchRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/public/ingestion',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(ingestionBatchRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IngestionApi - functional programming interface
 * @export
 */
export const IngestionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IngestionApiAxiosParamCreator(configuration)
    return {
        /**
         * Batched ingestion for Langfuse Tracing
         * @param {IngestionApiBatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async batch(requestParameters: IngestionApiBatchRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IngestionResponse>> {
            const ingestionBatchRequest: IngestionBatchRequest = {
                batch: requestParameters.batch
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.batch(ingestionBatchRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * IngestionApi - factory interface
 * @export
 */
export const IngestionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IngestionApiFp(configuration)
    return {
        /**
         * Batched ingestion for Langfuse Tracing
         * @param {IngestionApiBatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batch(requestParameters: IngestionApiBatchRequest, options?: AxiosRequestConfig): AxiosPromise<IngestionResponse> {
            return localVarFp.batch(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for batch operation in IngestionApi.
 * @export
 * @interface IngestionApiBatchRequest
 */
export type IngestionApiBatchRequest = {
    
} & IngestionBatchRequest

/**
 * IngestionApiGenerated - object-oriented interface
 * @export
 * @class IngestionApiGenerated
 * @extends {BaseAPI}
 */
export class IngestionApiGenerated extends BaseAPI {
    /**
     * Batched ingestion for Langfuse Tracing
     * @param {IngestionApiBatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestionApiGenerated
     */
    public batch(requestParameters: IngestionApiBatchRequest, options?: AxiosRequestConfig) {
        return IngestionApiFp(this.configuration).batch(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
