/* tslint:disable */
/* eslint-disable */
/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Trace } from '../models';
// @ts-ignore
import { Traces } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * TraceApi - axios parameter creator
 * @export
 */
export const TraceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a specific trace
         * @param {string} traceId The unique langfuse identifier of a trace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (traceId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'traceId' is not null or undefined
            assertParamExists('get', 'traceId', traceId)
            const localVarPath = `/api/public/traces/{traceId}`
                .replace(`{${"traceId"}}`, encodeURIComponent(String(traceId !== undefined ? traceId : `-traceId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/public/traces/{traceId}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get list of traces
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [userId] 
         * @param {string} [name] 
         * @param {string} [orderBy] Format of the string [field].[asc/desc]. Fields: id, timestamp, name, userId, release, version, public, bookmarked, sessionId. Example: timestamp.asc
         * @param {Array<string>} [tags] Only traces that include all of these tags will be returned.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (page?: number, limit?: number, userId?: string, name?: string, orderBy?: string, tags?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/public/traces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BasicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/public/traces',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TraceApi - functional programming interface
 * @export
 */
export const TraceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TraceApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a specific trace
         * @param {TraceApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(requestParameters: TraceApiGetRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Trace>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(requestParameters.traceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get list of traces
         * @param {TraceApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(requestParameters: TraceApiListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Traces>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(requestParameters.page, requestParameters.limit, requestParameters.userId, requestParameters.name, requestParameters.orderBy, requestParameters.tags, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TraceApi - factory interface
 * @export
 */
export const TraceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TraceApiFp(configuration)
    return {
        /**
         * Get a specific trace
         * @param {TraceApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(requestParameters: TraceApiGetRequest, options?: AxiosRequestConfig): AxiosPromise<Trace> {
            return localVarFp.get(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get list of traces
         * @param {TraceApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: TraceApiListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<Traces> {
            return localVarFp.list(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for get operation in TraceApi.
 * @export
 * @interface TraceApiGetRequest
 */
export type TraceApiGetRequest = {
    
    /**
    * The unique langfuse identifier of a trace
    * @type {string}
    * @memberof TraceApiGet
    */
    readonly traceId: string
    
}

/**
 * Request parameters for list operation in TraceApi.
 * @export
 * @interface TraceApiListRequest
 */
export type TraceApiListRequest = {
    
    /**
    * 
    * @type {number}
    * @memberof TraceApiList
    */
    readonly page?: number
    
    /**
    * 
    * @type {number}
    * @memberof TraceApiList
    */
    readonly limit?: number
    
    /**
    * 
    * @type {string}
    * @memberof TraceApiList
    */
    readonly userId?: string
    
    /**
    * 
    * @type {string}
    * @memberof TraceApiList
    */
    readonly name?: string
    
    /**
    * Format of the string [field].[asc/desc]. Fields: id, timestamp, name, userId, release, version, public, bookmarked, sessionId. Example: timestamp.asc
    * @type {string}
    * @memberof TraceApiList
    */
    readonly orderBy?: string
    
    /**
    * Only traces that include all of these tags will be returned.
    * @type {Array<string>}
    * @memberof TraceApiList
    */
    readonly tags?: Array<string>
    
}

/**
 * TraceApiGenerated - object-oriented interface
 * @export
 * @class TraceApiGenerated
 * @extends {BaseAPI}
 */
export class TraceApiGenerated extends BaseAPI {
    /**
     * Get a specific trace
     * @param {TraceApiGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TraceApiGenerated
     */
    public get(requestParameters: TraceApiGetRequest, options?: AxiosRequestConfig) {
        return TraceApiFp(this.configuration).get(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get list of traces
     * @param {TraceApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TraceApiGenerated
     */
    public list(requestParameters: TraceApiListRequest = {}, options?: AxiosRequestConfig) {
        return TraceApiFp(this.configuration).list(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
