/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BaseEvent
 */
export interface BaseEvent {
    /**
     * 
     * @type {string}
     * @memberof BaseEvent
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BaseEvent
     */
    'timestamp': string;
    /**
     * 
     * @type {any}
     * @memberof BaseEvent
     */
    'metadata': any;
}

