/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreatePromptRequest
 */
export interface CreatePromptRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePromptRequest
     */
    'name': string;
    /**
     * Should the prompt be promoted to production immediately?
     * @type {boolean}
     * @memberof CreatePromptRequest
     */
    'isActive': boolean;
    /**
     * 
     * @type {string}
     * @memberof CreatePromptRequest
     */
    'prompt': string;
    /**
     * 
     * @type {any}
     * @memberof CreatePromptRequest
     */
    'config'?: any | null;
}

