/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DailyMetricsDetails } from './daily-metrics-details';
import { UtilsMetaResponse } from './utils-meta-response';

/**
 * 
 * @export
 * @interface DailyMetrics
 */
export interface DailyMetrics {
    /**
     * A list of daily metrics, only days with ingested data are included.
     * @type {Array<DailyMetricsDetails>}
     * @memberof DailyMetrics
     */
    'data': Array<DailyMetricsDetails>;
    /**
     * 
     * @type {UtilsMetaResponse}
     * @memberof DailyMetrics
     */
    'meta': UtilsMetaResponse;
}

