/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IngestionError
 */
export interface IngestionError {
    /**
     * 
     * @type {string}
     * @memberof IngestionError
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof IngestionError
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof IngestionError
     */
    'message'?: string | null;
    /**
     * 
     * @type {any}
     * @memberof IngestionError
     */
    'error'?: any | null;
}

