/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IngestionEvent } from './ingestion-event';

/**
 * 
 * @export
 * @interface IngestionBatchRequest
 */
export interface IngestionBatchRequest {
    /**
     * 
     * @type {Array<IngestionEvent>}
     * @memberof IngestionBatchRequest
     */
    'batch': Array<IngestionEvent>;
}

