/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Observation } from './observation';
import { UtilsMetaResponse } from './utils-meta-response';

/**
 * 
 * @export
 * @interface ObservationsViews
 */
export interface ObservationsViews {
    /**
     * 
     * @type {Array<Observation>}
     * @memberof ObservationsViews
     */
    'data': Array<Observation>;
    /**
     * 
     * @type {UtilsMetaResponse}
     * @memberof ObservationsViews
     */
    'meta': UtilsMetaResponse;
}

