/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Usage interface of OpenAI for improved compatibility.
 * @export
 * @interface OpenAIUsage
 */
export interface OpenAIUsage {
    /**
     * 
     * @type {number}
     * @memberof OpenAIUsage
     */
    'promptTokens'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OpenAIUsage
     */
    'completionTokens'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OpenAIUsage
     */
    'totalTokens'?: number | null;
}

