/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObservationLevel } from './observation-level';

/**
 * 
 * @export
 * @interface OptionalObservationBody
 */
export interface OptionalObservationBody {
    /**
     * 
     * @type {string}
     * @memberof OptionalObservationBody
     */
    'version'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OptionalObservationBody
     */
    'traceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OptionalObservationBody
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OptionalObservationBody
     */
    'startTime'?: string | null;
    /**
     * 
     * @type {any}
     * @memberof OptionalObservationBody
     */
    'metadata'?: any | null;
    /**
     * 
     * @type {any}
     * @memberof OptionalObservationBody
     */
    'input'?: any | null;
    /**
     * 
     * @type {any}
     * @memberof OptionalObservationBody
     */
    'output'?: any | null;
    /**
     * 
     * @type {ObservationLevel}
     * @memberof OptionalObservationBody
     */
    'level'?: ObservationLevel;
    /**
     * 
     * @type {string}
     * @memberof OptionalObservationBody
     */
    'statusMessage'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OptionalObservationBody
     */
    'parentObservationId'?: string | null;
}

