/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ScoreBody
 */
export interface ScoreBody {
    /**
     * 
     * @type {string}
     * @memberof ScoreBody
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScoreBody
     */
    'traceId': string;
    /**
     * 
     * @type {string}
     * @memberof ScoreBody
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ScoreBody
     */
    'value': number;
    /**
     * 
     * @type {string}
     * @memberof ScoreBody
     */
    'observationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScoreBody
     */
    'comment'?: string | null;
}

