/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ScoreSource } from './score-source';

/**
 * 
 * @export
 * @interface Score
 */
export interface Score {
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    'traceId': string;
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof Score
     */
    'value': number;
    /**
     * 
     * @type {ScoreSource}
     * @memberof Score
     */
    'source': ScoreSource;
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    'observationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    'timestamp': string;
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    'comment'?: string | null;
}

