/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Score } from './score';
import { UtilsMetaResponse } from './utils-meta-response';

/**
 * 
 * @export
 * @interface Scores
 */
export interface Scores {
    /**
     * 
     * @type {Array<Score>}
     * @memberof Scores
     */
    'data': Array<Score>;
    /**
     * 
     * @type {UtilsMetaResponse}
     * @memberof Scores
     */
    'meta': UtilsMetaResponse;
}

