/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Trace } from './trace';
import { UtilsMetaResponse } from './utils-meta-response';

/**
 * 
 * @export
 * @interface Traces
 */
export interface Traces {
    /**
     * 
     * @type {Array<Trace>}
     * @memberof Traces
     */
    'data': Array<Trace>;
    /**
     * 
     * @type {UtilsMetaResponse}
     * @memberof Traces
     */
    'meta': UtilsMetaResponse;
}

