/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Daily usage of a given model. Usage corresponds to the unit set for the specific model (e.g. tokens).
 * @export
 * @interface UsageByModel
 */
export interface UsageByModel {
    /**
     * 
     * @type {string}
     * @memberof UsageByModel
     */
    'model': string;
    /**
     * 
     * @type {number}
     * @memberof UsageByModel
     */
    'inputUsage': number;
    /**
     * 
     * @type {number}
     * @memberof UsageByModel
     */
    'outputUsage': number;
    /**
     * 
     * @type {number}
     * @memberof UsageByModel
     */
    'totalUsage': number;
}

