/*
langfuse

## Authentication

Authenticate with the API using Basic Auth, get API keys in the project settings:

- username: Langfuse Public Key
- password: Langfuse Secret Key

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UtilsMetaResponse
 */
export interface UtilsMetaResponse {
    /**
     * current page number
     * @type {number}
     * @memberof UtilsMetaResponse
     */
    'page': number;
    /**
     * number of items per page
     * @type {number}
     * @memberof UtilsMetaResponse
     */
    'limit': number;
    /**
     * number of total items given the current filters/selection (if any)
     * @type {number}
     * @memberof UtilsMetaResponse
     */
    'totalItems': number;
    /**
     * number of total pages given the current limit
     * @type {number}
     * @memberof UtilsMetaResponse
     */
    'totalPages': number;
}

